variables:
  CARGO_HOME: ".cargo"

cache:
  key:
    files:
      - Cargo.lock
  paths:  
    # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
    - $CARGO_HOME/.crates.toml
    - $CARGO_HOME/.crates2.json
    - $CARGO_HOME/bin/
    - $CARGO_HOME/registry/index/
    - $CARGO_HOME/registry/cache/
    - $CARGO_HOME/git/db/
    - target

stages:
  - test
  - dist

test-linux:
  stage: test
  image: rust:latest
  script:
    - cargo test

test-macos:
  stage: test
  tags:
    - macos
  script:
    - cargo test

test-windows:
  stage: test
  tags:
    - windows
  variables:
    RUSTUP_HOME: "C:\\Users\\Public\\.rustup"
    CARGO_BIN: "C:\\Users\\Public\\.cargo\\bin"
  before_script:
    - set PATH=%PATH%;%CARGO_BIN%
  script:
    - cargo test

lint:
  stage: test
  image: rust:latest
  script:
    - rustup component add rustfmt clippy
    - cargo clippy --all-features --all-targets -- -D warnings
    - cargo fmt -- --check

dist-macos:
  stage: dist
  tags:
    - macos
  script:
    - cargo build --release --target x86_64-apple-darwin
    - scripts/dist_macos.sh
  artifacts:
    paths:
      - target/x86_64-apple-darwin/release/*.pkg

dist-windows:
  stage: dist
  tags:
    - windows
  variables:
    RUSTUP_HOME: "C:\\Users\\Public\\.rustup"
    CARGO_BIN: "C:\\Users\\Public\\.cargo\\bin"
  before_script:
    - set PATH=%PATH%;%CARGO_BIN%
  script:
    - pwsh scripts/dist_windows.ps1
  artifacts:
    paths:
      - glyphs_exchange/target/wix/*.msi
