[workspace]
members = [
    "glyphs_exchange",
    "glyphs_plist",
    "glyphs_plist_derive",
]

[workspace.dependencies]
norad = { version = "0.10", features = ["rayon", "kurbo"] }
kurbo = "0.9.2"

[profile.release]
debug = true
overflow-checks = true
lto = "thin"
